### PR TITLE
Fix react import syntax; linting changes

### PR DESCRIPTION
**Pull request by petermikitsh**
In newer versions of React Native, you import React from the `react` module (previously was from `react-native`). This PR will work with react native `0.41`.

Also made some style changes since my linter was yelling at me.

### CODE REVIEW

**Comment by TaylorBriggs** [comment]
@petermikitsh thanks for the PR! What are you using for your linter?

**Comment by TaylorBriggs** [comment]
I ask because I'd like to add a config and get the linting standardized for myself and other contributors.

**Comment by petermikitsh** [comment]
@TaylorBriggs [my linter file](https://gist.github.com/petermikitsh/0dabc9a96ffbe3479543076b4dc64567)

You'd also want to add `eslint` and `eslint-plugin-react` as devDependencies with it.

Since you don't have a CI job for this module, I'd also recommend adding pre-commit hook that will reject commits that fail linter validation. (You can always force push to get around them with `--force` in the commit message).

If you'd like me to add all of this, none of it, or varying parts to this PR let me know, thanks

**Comment by petermikitsh** [comment]
For the commit hook functionality, the additions would look something like this:

```js
{
  "scripts": {
    "lint": "eslint **/*.js"
  },
  "pre-commit": [
    "lint"
  ],
  devDependencies: {
    "pre-commit": "1.2.2"
  }
}
```

**Comment by TaylorBriggs** [comment]
@petermikitsh feel free to add all of those. I've used ESLint in other projects and I'm quite fond of it. You can also use [eslint-config-airbnb](https://www.npmjs.com/package/eslint-config-airbnb) and the "extends" option in `.eslintrc` to get those rules without rewriting them. It looks like there's also a [React Native plugin](https://www.npmjs.com/package/eslint-plugin-react-native).

The only reason I don't have CI set up here is I couldn't figure out how to write tests for React Native and this started out as a personal project. The pre-commit hook looks like a great start for running the lint script, at least.

**Comment by petermikitsh** [comment]
@TaylorBriggs alright changes added

**Comment by TaylorBriggs** [comment]
@petermikitsh Thanks!

**Pull request merged**
